### PR TITLE
Basic table filtering by column (text input and dropdowns), stashing …

### PR DESCRIPTION
**Pull request by mvpoyatt**
…progress

### CODE REVIEW

**Comment by Inkvi** [comment]
Where can I see how the changes look like?

**Comment by dshiell** [comment]
@Inkvi you should be able to run the stack locally and it will populate with mock data. Correct me if I am mistaken @mvpoyatt but that's what I was able to do previously.

**Comment by dshiell** [comment]
Screenshot 2024-02-21 at 4 37 27 PM

**Review by dshiell — APPROVED** [review]

**Comment by mvpoyatt** [comment]
@Inkvi Yea there's mock data being populated by default so you should be able to see it with just `npm run dev`

**Pull request merged**
